name: deploy order

on:
  push:
    branches:
      - main

jobs:
  #job name : 자유롭게 명세 가능
  build-and-deploy:
    # runner 
    runs-on: ubuntu-latest
    steps:
      - name:
        # 명령어
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3